---
abstract: 'WebKit2 bindings for Perl'
author:
  - 'Jason Shaun Carty <jc@atikon.com>'
  - 'Philipp Voglhofer <pv@atikon.com>'
  - 'Philipp A. Lehner <pl@atikon.com>'
build_requires:
  Test::NeedsDisplay: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk3-WebKit2
requires:
  Glib::Object::Introspection: 0
  Gtk3: 0
version: 0.06
